version: "3.9"

services:
  datadog:
    image: datadog/agent:latest
    container_name: "datadog"
    environment:
      - DD_API_KEY=<api key>
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=false
      - DD_CONTAINER_INCLUDE="image:spring-petclinic_frontend"
      - DD_CONTAINER_EXCLUDE="name:datadog-agent name:database"
      - DD_SITE=datadoghq.eu 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/opt/datadog-agent/run:/opt/datadog-agent/run:rw"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
      - "./logs:/var/lib/docker/containers"
    restart: unless-stopped
